from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'), 
    path('profile/<str:uemail>', views.profile, name='profile'), 
    path('profile2/<str:uemail>', views.profile2, name='profile2'), 
    path('upload/', views.upload, name='upload'), 
    path('login/', views.login, name='login'),
    path('login/login_ok', views.login_ok, name='login_ok'), 
    path('register/', views.register, name='register'), 
    path('register/register_ok', views.register_ok, name='register_ok'), 
    path('email_test/', views.email_test, name='email_test'),
    path('email_test/email_ok', views.email_ok, name='email_ok'),
    path('stream/<int:id>', views.stream, name='stream'), 
    path('stream/comment_ok/<int:id>', views.comment_ok, name='comment_ok'), 
    path('stream2/<int:pid>', views.stream2, name='stream'), 
    path('stream2/comment_ok/<int:pid>', views.comment_ok2, name='comment_ok'), 
    path('upload/upload_ok', views.upload_ok, name='upload_ok'),
    path("login/forgot_email/", views.forgot_email, name ='forgot_email'),
    path("login/forgot_email/forgot_email_ok", views.forgot_email_ok, name ='forgot_email_ok'),
    path("logout/", views.logout, name ='logout'),
    path('code_check/', views.code_check, name='code_check'),
    path('code_check/code_check_ok', views.code_check_ok, name='code_check_ok'),
    path('Int/', views.Int, name='Int'), 
    path('Int/Int_ok', views.Int_ok, name='Int_ok'), 
    path('profilephoto/', views.profilephoto, name='profilephoto'), 
    path('profilephoto/profilephoto_ok', views.profilephoto_ok, name='profilephoto_ok'), 
    path('newPlaylist/<int:id>', views.newPlaylist, name='newPlaylist'), 
    path('addPlaylist/<int:id>', views.addPlaylist, name='addPlaylist'), 
    path('newPlaylist/newPlaylist_ok/<int:id>', views.newPlaylist_ok, name='newPlaylist_ok'), 
    path('addPlaylist/addPlaylist_ok/<int:id>', views.addPlaylist_ok, name='addPlaylist_ok'), 
    path("account/", views.account, name ='account'),
    path("account/account_ok", views.account_ok, name ='account_ok'),
    path("login/forgot_pwd/", views.forgot_pwd, name ='forgot_pwd'),
    path('login/forgot_pwd/forgot_pwd_ok', views.forgot_pwd_ok, name='forgot_pwd_ok'),
    path('forgot_code_check/', views.forgot_code_check, name='forgot_code_check'),
    path('forgot_code_check/forgot_code_check_ok', views.forgot_code_check_ok, name='forgot_code_check_ok'),
    path('password_Edit/', views.password_Edit, name='password_Edit'),
    path('password_Edit/password_Edit_ok', views.password_Edit_ok, name='password_Edit_ok'),
    path('delete/<int:id>', views.delete, name='delete'), 
    path('delete2/<int:pid>', views.delete2, name='delete2'), 
    path('withdrawal/', views.withdrawal, name='withdrawal'), 
    path('withdrawal/withdrawal_ok', views.withdrawal_ok, name='withdrawal_ok'), 
]