# Generated by Django 4.1.7 on 2023-03-03 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mphoto",
                    models.ImageField(blank=True, null=True, upload_to="upload/image"),
                ),
                ("mp3", models.FileField(upload_to="upload/music")),
                ("mtitle", models.CharField(max_length=45)),
                ("msinger", models.CharField(max_length=45)),
                ("mdesc", models.TextField(blank=True)),
                ("mgenre", models.CharField(max_length=15)),
                ("mrdate", models.DateTimeField()),
                ("mudate", models.DateTimeField()),
                ("mview", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "uemail",
                    models.EmailField(max_length=30, primary_key=True, serialize=False),
                ),
                ("uname", models.CharField(max_length=12)),
                ("upwd", models.CharField(max_length=12)),
                ("unick", models.CharField(max_length=30, unique=True)),
                ("urdate", models.DateTimeField()),
                (
                    "uimage",
                    models.ImageField(
                        blank=True, null=True, upload_to="upload/profile"
                    ),
                ),
                ("utel", models.CharField(max_length=11)),
                ("udesc", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pname", models.CharField(max_length=40)),
                (
                    "mid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soosnimbus.music",
                    ),
                ),
                (
                    "uemail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soosnimbus.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="music",
            name="uemail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="soosnimbus.user"
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cdesc", models.TextField()),
                ("crdate", models.DateTimeField()),
                (
                    "mid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soosnimbus.music",
                    ),
                ),
                (
                    "uemail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soosnimbus.user",
                    ),
                ),
            ],
        ),
    ]
